name: Pull Request Build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  SOLUTION: src/Standard.Licensing.sln

jobs:
  pull_request:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1

    - name: Build
      run: |
        $Branch = "${{ github.base_ref }}" -replace '(refs/tags/)(.+)', '$2'
        $VERSION = Get-Content 'version' -TotalCount 1
        $PACKAGE_VERSION = "$VERSION-pr.${{ github.run_number }}"
        Write-Output "Generating Package with version: $PACKAGE_VERSION ..."
        dotnet pack '${{ env.SOLUTION }}' -o dist -p:Configuration=Release -p:Version=$VERSION -p:PackageVersion=$PACKAGE_VERSION -p:RepositoryType=git -p:RepositoryUrl=https://github.com/${{ github.repository }}.git -p:RepositoryBranch=$Branch -p:RepositoryCommit=${{ github.sha }}

    - name: Upload artifact
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: dist/*.nupkg
